CREATE TABLE Team ( id INTEGER PRIMARY KEY  ,
team_api_id INTEGER UNIQUE,
team_fifa_api_id INTEGER UNIQUE NOT NULL,
team_long_name VARCHAR(500),
team_short_name VARCHAR(500) );



CREATE TABLE Player ( id INTEGER PRIMARY KEY ,
player_api_id INTEGER UNIQUE,
player_name VARCHAR(500),
player_fifa_api_id INTEGER UNIQUE,
birthday VARCHAR(500),
height INTEGER,
weight INTEGER );



CREATE TABLE Country ( id INTEGER PRIMARY KEY,
name VARCHAR(500) UNIQUE ); 



CREATE TABLE League ( id INTEGER PRIMARY KEY,
country_id INTEGER,
name VARCHAR(500) UNIQUE,
FOREIGN KEY(country_id) REFERENCES Country(id) );


CREATE TABLE Player_Attributes ( id INTEGER PRIMARY KEY ,
player_fifa_api_id INTEGER,
player_api_id INTEGER,
date VARCHAR(500),
overall_rating INTEGER,
potential INTEGER,
preferred_foot VARCHAR(500),
attacking_work_rate VARCHAR(500),
defensive_work_rate VARCHAR(500),
crossing INTEGER,
finishing INTEGER,
heading_accuracy INTEGER,
short_passing INTEGER,
volleys INTEGER,
dribbling INTEGER,
curve INTEGER,
free_kick_accuracy INTEGER,
long_passing INTEGER,
ball_control INTEGER,
acceleration INTEGER,
sprint_speed INTEGER,
agility INTEGER,
reactions INTEGER,
balance INTEGER,
shot_power INTEGER,
jumping INTEGER,
stamina INTEGER,
strength INTEGER,
long_shots INTEGER,
aggression INTEGER,
interceptions INTEGER,
positioning INTEGER,
vision INTEGER,
penalties INTEGER,
marking INTEGER,
standing_tackle INTEGER,
sliding_tackle INTEGER,
gk_diving INTEGER,
gk_handling INTEGER,
gk_kicking INTEGER,
gk_positioning INTEGER,
gk_reflexes INTEGER,
FOREIGN KEY(player_fifa_api_id) REFERENCES Player(player_fifa_api_id),
FOREIGN KEY(player_api_id) REFERENCES Player(player_api_id) )
;

SELECT * FROM League


CREATE TABLE Team_Attributes ( id INTEGER PRIMARY KEY ,
team_fifa_api_id INTEGER,
team_api_id INTEGER,
date VARCHAR(500),
buildUpPlaySpeed INTEGER,
buildUpPlaySpeedClass VARCHAR(500),
buildUpPlayDribbling INTEGER,
buildUpPlayDribblingClass VARCHAR(500),
buildUpPlayPassing INTEGER,
buildUpPlayPassingClass VARCHAR(500),
buildUpPlayPositioningClass VARCHAR(500),
chanceCreationPassing INTEGER,
chanceCreationPassingClass VARCHAR(500),
chanceCreationCrossing INTEGER,
chanceCreationCrossingClass VARCHAR(500),
chanceCreationShooting INTEGER,
chanceCreationShootingClass VARCHAR(500),
chanceCreationPositioningClass VARCHAR(500),
defencePressure INTEGER,
defencePressureClass VARCHAR(500),
defenceAggression INTEGER,
defenceAggressionClass VARCHAR(500),
defenceTeamWidth INTEGER,
defenceTeamWidthClass VARCHAR(500),
defenceDefenderLineClass VARCHAR(500));

ALTER TABLE Team_Attributes
ADD CONSTRAINT fk_from_attr_to_team_2 FOREIGN KEY(team_fifa_api_id) REFERENCES Team(team_fifa_api_id);

ALTER TABLE Team_Attributes
ADD CONSTRAINT fk_from_attr_to_team_1 FOREIGN KEY(team_api_id) REFERENCES Team(team_api_id);


CREATE TABLE Match ( id INTEGER PRIMARY KEY ,
country_id INTEGER,
league_id INTEGER,
season VARCHAR(500),
stage INTEGER,
date VARCHAR(500),
match_api_id INTEGER,
home_team_api_id INTEGER,
away_team_api_id INTEGER,
home_team_goal INTEGER,
away_team_goal INTEGER,
home_player_X1 INTEGER,
home_player_X2 INTEGER,
home_player_X3 INTEGER,
home_player_X4 INTEGER,
home_player_X5 INTEGER,
home_player_X6 INTEGER,
home_player_X7 INTEGER,
home_player_X8 INTEGER,
home_player_X9 INTEGER,
home_player_X10 INTEGER,
home_player_X11 INTEGER,
away_player_X1 INTEGER,
away_player_X2 INTEGER,
away_player_X3 INTEGER,
away_player_X4 INTEGER,
away_player_X5 INTEGER,
away_player_X6 INTEGER,
away_player_X7 INTEGER,
away_player_X8 INTEGER,
away_player_X9 INTEGER,
away_player_X10 INTEGER,
away_player_X11 INTEGER,
home_player_Y1 INTEGER,
home_player_Y2 INTEGER,
home_player_Y3 INTEGER,
home_player_Y4 INTEGER,
home_player_Y5 INTEGER,
home_player_Y6 INTEGER,
home_player_Y7 INTEGER,
home_player_Y8 INTEGER,
home_player_Y9 INTEGER,
home_player_Y10 INTEGER,
home_player_Y11 INTEGER,
away_player_Y1 INTEGER,
away_player_Y2 INTEGER,
away_player_Y3 INTEGER,
away_player_Y4 INTEGER,
away_player_Y5 INTEGER,
away_player_Y6 INTEGER,
away_player_Y7 INTEGER,
away_player_Y8 INTEGER,
away_player_Y9 INTEGER,
away_player_Y10 INTEGER,
away_player_Y11 INTEGER,
home_player_1 INTEGER,
home_player_2 INTEGER,
home_player_3 INTEGER,
home_player_4 INTEGER,
home_player_5 INTEGER,
home_player_6 INTEGER,
home_player_7 INTEGER,
home_player_8 INTEGER,
home_player_9 INTEGER,
home_player_10 INTEGER,
home_player_11 INTEGER,
away_player_1 INTEGER,
away_player_2 INTEGER,
away_player_3 INTEGER,
away_player_4 INTEGER,
away_player_5 INTEGER,
away_player_6 INTEGER,
away_player_7 INTEGER,
away_player_8 INTEGER,
away_player_9 INTEGER,
away_player_10 INTEGER,
away_player_11 INTEGER,
goal TEXT,
shoton TEXT,
shotoff TEXT,
foulcommit TEXT,
card TEXT,
crossX TEXT,
corner TEXT,
possession TEXT,
B365H NUMERIC,
B365D NUMERIC,
B365A NUMERIC,
BWH NUMERIC,
BWD NUMERIC,
BWA NUMERIC,
IWH NUMERIC,
IWD NUMERIC,
IWA NUMERIC,
LBH NUMERIC,
LBD NUMERIC,
LBA NUMERIC,
PSH NUMERIC,
PSD NUMERIC,
PSA NUMERIC,
WHH NUMERIC,
WHD NUMERIC,
WHA NUMERIC,
SJH NUMERIC,
SJD NUMERIC,
SJA NUMERIC,
VCH NUMERIC,
VCD NUMERIC,
VCA NUMERIC,
GBH NUMERIC,
GBD NUMERIC,
GBA NUMERIC,
BSH NUMERIC,
BSD NUMERIC,
BSA NUMERIC
FOREIGN KEY(country_id) REFERENCES Country(id),
FOREIGN KEY(league_id) REFERENCES League(id),
FOREIGN KEY(home_team_api_id) REFERENCES Team(team_api_id),
FOREIGN KEY(away_team_api_id) REFERENCES Team(team_api_id),
--CONSTRAINT stupid1 FOREIGN KEY(home_player_1) REFERENCES Player(player_api_id),
--CONSTRAINT stupid2 FOREIGN KEY(home_player_2) REFERENCES Player(player_api_id),
--CONSTRAINT stupid3 FOREIGN KEY(home_player_3) REFERENCES Player(player_api_id),
--CONSTRAINT stupid4 FOREIGN KEY(home_player_4) REFERENCES Player(player_api_id),
--CONSTRAINT stupid5 FOREIGN KEY(home_player_5) REFERENCES Player(player_api_id),
--CONSTRAINT stupid6 FOREIGN KEY(home_player_6) REFERENCES Player(player_api_id),
----CONSTRAINT stupid7 FOREIGN KEY(home_player_7) REFERENCES Player(player_api_id),
--CONSTRAINT stupid8 FOREIGN KEY(home_player_8) REFERENCES Player(player_api_id),
--CONSTRAINT stupid9 FOREIGN KEY(home_player_9) REFERENCES Player(player_api_id),
--CONSTRAINT stupid10 FOREIGN KEY(home_player_10) REFERENCES Player(player_api_id),
--CONSTRAINT stupid11 FOREIGN KEY(home_player_11) REFERENCES Player(player_api_id),
----CONSTRAINT stupid12 FOREIGN KEY(away_player_1) REFERENCES Player(player_api_id),
--CONSTRAINT stupid13 FOREIGN KEY(away_player_2) REFERENCES Player(player_api_id),
--CONSTRAINT stupid14 FOREIGN KEY(away_player_3) REFERENCES Player(player_api_id),
--CONSTRAINT stupid15 FOREIGN KEY(away_player_4) REFERENCES Player(player_api_id),
--CONSTRAINT stupid16 FOREIGN KEY(away_player_5) REFERENCES Player(player_api_id),
--CONSTRAINT stupid17 FOREIGN KEY(away_player_6) REFERENCES Player(player_api_id),
--CONSTRAINT stupid18 FOREIGN KEY(away_player_7) REFERENCES Player(player_api_id),
--CONSTRAINT stupid19 FOREIGN KEY(away_player_8) REFERENCES Player(player_api_id),
--CONSTRAINT stupid20 FOREIGN KEY(away_player_9) REFERENCES Player(player_api_id),
--CONSTRAINT stupid21 FOREIGN KEY(away_player_10) REFERENCES Player(player_api_id),
--CONSTRAINT stupid22 FOREIGN KEY(away_player_11) REFERENCES Player(player_api_id) 
)
